### PR TITLE
Api changes

### PR DESCRIPTION
**Pull request by Pharylon**
These changes allow for the API to handle matches between two local bots

### CODE REVIEW

**Comment by Pharylon** [comment]
This 99% only affects the API that my local debug assistant uses (I also got a slight change to the WarView Hub in this so it can update player names and win/loss colors better because I forgot what branch I was in when I did it). Anyway, all that being said, to test this, you'll need the newest version of the Debugger I just committed (the compiled download WILL NOT WORK, it's still on the old/current version of the API). 

I'm not sure how much @Dubman25 has stepped away, or if he's still reviewing Pull Requests. If he isn't doing that anymore, @Pabreetzio, feel free to let me know if you just don't want to do the code review and I can go ahead and merge this myself.

Oh, also, I need to be the one to hit the big green button once (if) the review is done. My Deug Assitant checks for new versions of itself on launch, and once we merge, I need to update the version number on the download so it'll all be in sync.

**Comment by Pharylon** [comment]
By the way, I just reread my own words, and I don't want to sound eager for not having a code review. I'd prefer one. But I'd also like to have the new API up by tomorrow when people might use it. :D

**Comment by Pabreetzio** [comment]
Just looked over it, have't tested it. Only thing it noticed was, why do we have the unique constraints on bots? We shouldn't allow someone to know someone else's hidden URL just because they guessed at it and the unique constraint kicked it out. We had two bots use the same URL last tournament with different names because we didn't have enough entries. It seemed to add value to be able to do that.

**Comment by Pharylon** [comment]
I just thought it'd be something to keep people from cheating by entering the same bot in the tournament twice if we didn't want that. If you want to allow people to enter the same tournament twice with the same bot, that's fine, but if we're talking about guessing URLs, what about guessing the opponent's URL and entering it as my bot? What if I enter NotDivideByZer0, and point it at Keith's URL? :)

IMO, I think if we want to let someone enter the same bot twice, we should do it without the different names. But, I mean, I'm not married to the idea. I'm cool with whatever you want to do.

**Pull request merged**
